name: Lint
on: push

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - run: yarn eslint .
